Change zentyal actions to new script zentyal-maxcontrol using perl API

diff --git a/bin/max-control b/bin/max-control
--- a/bin/max-control
+++ b/bin/max-control
@@ -66,103 +66,131 @@ case $1 in
         PASSWD=$5
         ROLE=$6
         USHELL=$7
+        DESCRIPTION=$7
 
-        if wbinfo -i "$NEWUSER" >/dev/null 2>&1 ; then
+        if getent passwd "$NEWUSER" >/dev/null 2>&1 ; then
             echo_exit "exists"
         fi
 
         create_lock
 
+        USHELL="/bin/false"
         if [ "${USHELL}" = "" ]; then
             USHELL="/bin/false"
         fi
 
-        #DCNAME="$(samba-tool domain info 127.0.0.1 2>/dev/null| awk '/^DC name/ {print $4}')"
-        # max-server.madrid.local
-        DCNAME="$(dnsdomainname -f)"
-        
-
-        DRIVE="$(awk -F'"' '/drive/ {print $4}' /var/lib/zentyal/conf/samba.bak 2>/dev/null| tail -1)"
-        # H:
-        if [ "$DRIVE" = "" ]; then
-            DRIVE='H:'
-        fi
-
-        LDAP_ADMIN="$(awk -F"'" '/LDAP_ADMIN/ {print $2}' /etc/max-control/conf.inc.php)"
-        LDAP_PASSW="$(awk -F"'" '/LDAP_PASS/ {print $2}' /etc/max-control/conf.inc.php)"
-
-        mkdir -p "${HOMES_DIR}"
-        #set -x
-
-
-        # echo samba-tool user add \
-        #   "$NEWUSER" "$PASSWD" --use-username-as-cn --given-name="$NAME" --surname="$SURNAME" \
-        #   -U"${LDAP_ADMIN}":"${LDAP_PASSW}" \
-        #   --profile-path='\\\\'$DCNAME'\\profiles\\'$NEWUSER \
-        #   --home-directory='\\\\'$DCNAME'\\'$NEWUSER \
-        #   --home-drive="'$DRIVE'"
-
-        # create local user
-        #self.exe_cmd("useradd -m %s -p%s -s /bin/bash -d /home/%s" %(username, username, username))
-        #self.exe_cmd("echo %s:%s | chpasswd" %(username, username))
-        NEWUUID=$(max-get-newuser-uuid)
-
-        useradd -m "$NEWUSER" -s "${USHELL}" -d "${HOMES_DIR}/$NEWUSER" --no-user-group --uid="${NEWUUID}" || echo_exit "error"
-        echo "${NEWUSER}:${PASSWD}" | chpasswd
-        chown -R "${NEWUSER}:Domain Users" "${HOMES_DIR}/$NEWUSER"
-        chmod 700 "${HOMES_DIR}/$NEWUSER"
-
-
-        samba-tool user create \
-          "$NEWUSER" "$PASSWD" --use-username-as-cn --given-name="$NAME" --surname="$SURNAME" \
-          -U"${LDAP_ADMIN}":"${LDAP_PASSW}" \
-          --profile-path='\\'$DCNAME'\profiles\'$NEWUSER \
-          --home-directory='\\'$DCNAME'\'$NEWUSER \
-          --home-drive="$DRIVE" \
-          --rfc2307-from-nss --gecos "$NAME $SURNAME" \
-          --uid="$NEWUSER" --uid-number="${NEWUUID}" --login-shell="${USHELL}" || echo_exit "error"
-
-
-        #ldbsearch -H /opt/samba4/private/sam.ldb '(cn=aaa9)'
-
-        #NEWUUID=$(wbinfo --sid-to-uid `wbinfo --name-to-sid $NEWUSER | awk '{print $1}'`)
-        # NEWUUID=$(wbinfo -n $NEWUSER| awk -F" |\-" '{print $8}')
-        # NEWUUID=$((NEWUUID+50000))
-        #echo "NEWUUID=$NEWUUID"
-        NEWUUID=$(id -u "$NEWUSER")
-
-        mkdir -p "${PROFILES_DIR}/${NEWUSER}"
-        chown "${NEWUUID}":"Domain Users" "${PROFILES_DIR}/${NEWUSER}"
-        chmod 700 "${PROFILES_DIR}/${NEWUSER}"
-
-        setfacl -b "${PROFILES_DIR}/${NEWUSER}"    2>&1
-        setfacl -R -m u:root:rwx,g::---,g:"Domain Users":---,u:${NEWUUID}:rwx "${PROFILES_DIR}/${NEWUSER}" 2>&1
-        setfacl -R -m d:u:root:rwx,g::---,g:"Domain Users":---,u:${NEWUUID}:rwx "${PROFILES_DIR}/${NEWUSER}" 2>&1
-
-
-        QUOTA=$(max-control getdefaultquota)
+        QUOTA=2000
         case $ROLE in
             admin)
                 QUOTA=$((QUOTA*2))
-                samba-tool group addmembers "Administrators" "$NEWUSER"
-                samba-tool group addmembers "Group Policy Creator Owners" "$NEWUSER"
-                samba-tool group addmembers "Enterprise Admins" "$NEWUSER"
-                samba-tool group addmembers "Schema Admins" "$NEWUSER"
-                samba-tool group addmembers "Domain Admins" "$NEWUSER"
             ;;
             teacher)
                 QUOTA=$((QUOTA*2))
-                samba-tool group addmembers "Teachers" "$NEWUSER"
-            ;;
-            tic)
-                samba-tool group addmembers "CoordinadoresTIC" "$NEWUSER"
             ;;
         esac
-        /usr/bin/edit.quotas --set --user="${NEWUUID}" --size="$QUOTA" >/dev/null 2>&1
 
-        
+        #set -x
+        set -e
+
+        export USERNAME="${NEWUSER}"
+        export PASSWORD="${PASSWD}"
+        export NAME="${NAME}"
+        export SURNAME="${SURNAME}"
+        export DESCRIPTION="${DESCRIPTION}"
+        export ROLE="${ROLE}"
+        export USHELL="${USHELL}"
+        export QUOTA="${QUOTA}"
+
+        zentyal-maxcontrol adduser
         echo 'OK'
         exit 0
+
+        # #DCNAME="$(samba-tool domain info 127.0.0.1 2>/dev/null| awk '/^DC name/ {print $4}')"
+        # # max-server.madrid.local
+        # DCNAME="$(dnsdomainname -f)"
+        
+
+        # DRIVE="$(awk -F'"' '/drive/ {print $4}' /var/lib/zentyal/conf/samba.bak 2>/dev/null| tail -1)"
+        # # H:
+        # if [ "$DRIVE" = "" ]; then
+        #     DRIVE='H:'
+        # fi
+
+        # LDAP_ADMIN="$(awk -F"'" '/LDAP_ADMIN/ {print $2}' /etc/max-control/conf.inc.php)"
+        # LDAP_PASSW="$(awk -F"'" '/LDAP_PASS/ {print $2}' /etc/max-control/conf.inc.php)"
+
+        # mkdir -p "${HOMES_DIR}"
+        # #set -x
+
+
+        # # echo samba-tool user add \
+        # #   "$NEWUSER" "$PASSWD" --use-username-as-cn --given-name="$NAME" --surname="$SURNAME" \
+        # #   -U"${LDAP_ADMIN}":"${LDAP_PASSW}" \
+        # #   --profile-path='\\\\'$DCNAME'\\profiles\\'$NEWUSER \
+        # #   --home-directory='\\\\'$DCNAME'\\'$NEWUSER \
+        # #   --home-drive="'$DRIVE'"
+
+        # # create local user
+        # #self.exe_cmd("useradd -m %s -p%s -s /bin/bash -d /home/%s" %(username, username, username))
+        # #self.exe_cmd("echo %s:%s | chpasswd" %(username, username))
+        # NEWUUID=$(max-get-newuser-uuid)
+
+        # useradd -m "$NEWUSER" -s "${USHELL}" -d "${HOMES_DIR}/$NEWUSER" --no-user-group --uid="${NEWUUID}" || echo_exit "error"
+        # echo "${NEWUSER}:${PASSWD}" | chpasswd
+        # chown -R "${NEWUSER}:Domain Users" "${HOMES_DIR}/$NEWUSER"
+        # chmod 700 "${HOMES_DIR}/$NEWUSER"
+
+
+        # samba-tool user create \
+        #   "$NEWUSER" "$PASSWD" --use-username-as-cn --given-name="$NAME" --surname="$SURNAME" \
+        #   -U"${LDAP_ADMIN}":"${LDAP_PASSW}" \
+        #   --profile-path='\\'$DCNAME'\profiles\'$NEWUSER \
+        #   --home-directory='\\'$DCNAME'\'$NEWUSER \
+        #   --home-drive="$DRIVE" \
+        #   --rfc2307-from-nss --gecos "$NAME $SURNAME" \
+        #   --uid="$NEWUSER" --uid-number="${NEWUUID}" --login-shell="${USHELL}" || echo_exit "error"
+
+
+        # #ldbsearch -H /opt/samba4/private/sam.ldb '(cn=aaa9)'
+
+        # #NEWUUID=$(wbinfo --sid-to-uid `wbinfo --name-to-sid $NEWUSER | awk '{print $1}'`)
+        # # NEWUUID=$(wbinfo -n $NEWUSER| awk -F" |\-" '{print $8}')
+        # # NEWUUID=$((NEWUUID+50000))
+        # #echo "NEWUUID=$NEWUUID"
+        # NEWUUID=$(id -u "$NEWUSER")
+
+        # mkdir -p "${PROFILES_DIR}/${NEWUSER}"
+        # chown "${NEWUUID}":"Domain Users" "${PROFILES_DIR}/${NEWUSER}"
+        # chmod 700 "${PROFILES_DIR}/${NEWUSER}"
+
+        # setfacl -b "${PROFILES_DIR}/${NEWUSER}"    2>&1
+        # setfacl -R -m u:root:rwx,g::---,g:"Domain Users":---,u:${NEWUUID}:rwx "${PROFILES_DIR}/${NEWUSER}" 2>&1
+        # setfacl -R -m d:u:root:rwx,g::---,g:"Domain Users":---,u:${NEWUUID}:rwx "${PROFILES_DIR}/${NEWUSER}" 2>&1
+
+
+        # QUOTA=$(max-control getdefaultquota)
+        # case $ROLE in
+        #     admin)
+        #         QUOTA=$((QUOTA*2))
+        #         samba-tool group addmembers "Administrators" "$NEWUSER"
+        #         samba-tool group addmembers "Group Policy Creator Owners" "$NEWUSER"
+        #         samba-tool group addmembers "Enterprise Admins" "$NEWUSER"
+        #         samba-tool group addmembers "Schema Admins" "$NEWUSER"
+        #         samba-tool group addmembers "Domain Admins" "$NEWUSER"
+        #     ;;
+        #     teacher)
+        #         QUOTA=$((QUOTA*2))
+        #         samba-tool group addmembers "Teachers" "$NEWUSER"
+        #     ;;
+        #     tic)
+        #         samba-tool group addmembers "CoordinadoresTIC" "$NEWUSER"
+        #     ;;
+        # esac
+        # /usr/bin/edit.quotas --set --user="${NEWUUID}" --size="$QUOTA" >/dev/null 2>&1
+
+        
+        # echo 'OK'
+        # exit 0
 
 
 
@@ -244,14 +272,19 @@ case $1 in
         ;;
 ################################################################################
     deluser)
-        # username and surname
-        DELUSER=$2
-
+        
         create_lock
 
-        samba-tool user delete "$DELUSER" >/dev/null 2>&1 && echo 'OK'
-        deluser "$DELUSER" >/dev/null 2>&1
+        set -e
+        export USERNAME="$2"
+        zentyal-maxcontrol deluser
+        echo 'OK'
         exit 0
+
+        # DELUSER=$2
+        # samba-tool user delete "$DELUSER" >/dev/null 2>&1 && echo 'OK'
+        # deluser "$DELUSER" >/dev/null 2>&1
+        # exit 0
         ;;
 ################################################################################
     addcomputer)
